import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import {
  ArrowLeft,
  BookOpen,
  CheckCircle2,
  Edit3,
  Languages,
  Loader2,
  Plus,
  RefreshCw,
  Save,
  Search,
  Sparkles,
  Trash2,
} from 'lucide-react'
import { getAdminSession, getAdminToken, logoutAdmin } from '../lib/adminAuth'
import {
  getBookLanguageSummary,
  createBook as apiCreateBook,
  deleteBook as apiDeleteBook,
  fetchBooks,
  resetBooks as apiResetBooks,
  updateBook as apiUpdateBook,
} from '../lib/booksApi'

function slugifyBookTitle(title) {
  const slug = String(title || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

  return slug || 'book'
}

function createEmptyBook() {
  return {
    sku: '',
    title: '',
    author: '',
    cover: '/assets/demo.jpg',
    pages: '',
    price: '',
    description: '',
    uri: '',
    bilangual: false,
    onlyEnglish: true,
    onpunjabi: false,
  }
}

function toFormBook(book) {
  return {
    sku: book.sku || '',
    title: book.title || '',
    author: book.author || '',
    cover: book.cover || '/assets/demo.jpg',
    pages: String(book.pages ?? ''),
    price: String(Math.round(Number(book.pricePaise ?? book.price * 100 ?? 0) / 100)),
    description: book.description || '',
    uri: book.uri || '',
    bilangual: Boolean(book.bilangual),
    onlyEnglish: Boolean(book.onlyEnglish),
    onpunjabi: Boolean(book.onpunjabi),
  }
}

function formatCurrency(value) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(Number(value || 0))
}

function AdminBooksPage() {
  const navigate = useNavigate()
  const session = getAdminSession()
  const token = getAdminToken()

  const [books, setBooks] = useState([])
  const [form, setForm] = useState(() => createEmptyBook())
  const [editingSku, setEditingSku] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [filterMode, setFilterMode] = useState('all')
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(true)

  useEffect(() => {
    if (!token) {
      navigate('/admin/login', { replace: true })
    }
  }, [navigate, token])

  useEffect(() => {
    let active = true

    async function loadCatalog() {
      setLoading(true)
      setError('')
      try {
        const booksData = await fetchBooks()
        if (active) {
          setBooks(booksData)
        }
      } catch (loadError) {
        if (active) {
          setError(loadError.message || 'Unable to load books.')
        }
      } finally {
        if (active) {
          setLoading(false)
        }
      }
    }

    loadCatalog()

    return () => {
      active = false
    }
  }, [])

  const filteredBooks = useMemo(() => {
    const query = searchQuery.trim().toLowerCase()

    return books.filter((book) => {
      const language = getBookLanguageSummary(book)
      const matchesSearch =
        !query ||
        [book.title, book.author, book.sku, book.description, language]
          .filter(Boolean)
          .some((value) => String(value).toLowerCase().includes(query))

      const matchesFilter =
        filterMode === 'all' ||
        (filterMode === 'bilingual' && book.bilangual) ||
        (filterMode === 'english' && book.onlyEnglish) ||
        (filterMode === 'punjabi' && book.onpunjabi)

      return matchesSearch && matchesFilter
    })
  }, [books, filterMode, searchQuery])

  const stats = useMemo(
    () => [
      { label: 'Total books', value: books.length },
      { label: 'Bilingual', value: books.filter((book) => book.bilangual).length },
      { label: 'English', value: books.filter((book) => book.onlyEnglish).length },
      { label: 'Punjabi', value: books.filter((book) => book.onpunjabi).length },
    ],
    [books],
  )

  const resetForm = () => {
    setForm(createEmptyBook())
    setEditingSku('')
    setSkuAutoGenerated(true)
    setError('')
    setSuccess('')
  }

  const beginEditBook = (book) => {
    setForm(toFormBook(book))
    setEditingSku(book.sku)
    setSkuAutoGenerated(slugifyBookTitle(book.title) === book.sku)
    setError('')
    setSuccess('')
  }

  const handleFieldChange = (field, value) => {
    setForm((prev) => {
      const nextForm = { ...prev, [field]: value }

      if (field === 'title' && skuAutoGenerated) {
        nextForm.sku = slugifyBookTitle(value)
      }

      if (field === 'sku') {
        setSkuAutoGenerated(false)
      }

      return nextForm
    })
  }

  const handleBilingualToggle = (checked) => {
    setForm((prev) => ({
      ...prev,
      bilangual: checked,
      onlyEnglish: checked ? true : prev.onlyEnglish,
      onpunjabi: checked ? true : prev.onpunjabi,
    }))
  }

  const handleLanguageToggle = (field, checked) => {
    setForm((prev) => {
      const nextForm = { ...prev, [field]: checked }
      if (!checked && !nextForm.onlyEnglish && !nextForm.onpunjabi) {
        nextForm[field] = true
      }
      return nextForm
    })
  }

  const handleRefresh = () => {
    setLoading(true)
    setError('')
    setSuccess('')
    fetchBooks()
      .then((booksData) => {
        setBooks(booksData)
        setSuccess('Books refreshed from the database.')
      })
      .catch((loadError) => setError(loadError.message || 'Unable to refresh books.'))
      .finally(() => setLoading(false))
  }

  const handleResetCatalog = async () => {
    setLoading(true)
    setError('')
    setSuccess('')
    try {
      const defaults = await apiResetBooks(token)
      setBooks(defaults)
      resetForm()
      setSuccess('Default books restored in the database.')
    } catch (resetError) {
      setError(resetError.message || 'Unable to reset the catalog right now.')
    } finally {
      setLoading(false)
    }
  }

  const handleSaveBook = async (event) => {
    event.preventDefault()
    setError('')
    setSuccess('')

    const normalizedBook = {
      sku: form.sku.trim() || slugifyBookTitle(form.title),
      title: form.title.trim(),
      author: form.author.trim(),
      cover: form.cover || '/assets/demo.jpg',
      pages: Number(form.pages),
      price: Number(form.price),
      description: form.description.trim(),
      uri: form.uri.trim(),
      bilangual: Boolean(form.bilangual),
      onlyEnglish: Boolean(form.bilangual ? true : form.onlyEnglish),
      onpunjabi: Boolean(form.bilangual ? true : form.onpunjabi),
    }

    if (!normalizedBook.title) {
      setError('Please enter a title.')
      return
    }

    if (!normalizedBook.author) {
      setError('Please enter an author name.')
      return
    }

    if (!normalizedBook.pages || normalizedBook.pages <= 0) {
      setError('Please enter a valid number of pages.')
      return
    }

    if (!normalizedBook.price || normalizedBook.price <= 0) {
      setError('Please enter a valid price.')
      return
    }

    if (!normalizedBook.description) {
      setError('Please enter a description.')
      return
    }

    if (!normalizedBook.uri) {
      setError('Please enter the book image URI.')
      return
    }

    if (!normalizedBook.bilangual && !normalizedBook.onlyEnglish && !normalizedBook.onpunjabi) {
      setError('Choose bilingual or at least one language option.')
      return
    }

    try {
      setSaving(true)
      const savedBook = editingSku
        ? await apiUpdateBook(token, editingSku, normalizedBook)
        : await apiCreateBook(token, normalizedBook)

      setBooks((currentBooks) => {
        const nextBooks = [...currentBooks]
        const existingIndex = nextBooks.findIndex((book) => book.sku === savedBook.sku)

        if (existingIndex >= 0) {
          nextBooks[existingIndex] = savedBook
        } else {
          nextBooks.unshift(savedBook)
        }

        return nextBooks
      })

      setSuccess(editingSku ? 'Book updated successfully.' : 'Book added successfully.')
      setForm(createEmptyBook())
      setEditingSku('')
      setSkuAutoGenerated(true)
    } catch (saveError) {
      setError(saveError.message || 'Unable to save the book.')
    } finally {
      setSaving(false)
    }
  }

  const handleDeleteBook = async (bookSku) => {
    const book = books.find((entry) => entry.sku === bookSku)
    const confirmed = window.confirm(`Delete "${book?.title || 'this book'}" from the catalog?`)
    if (!confirmed) {
      return
    }

    try {
      await apiDeleteBook(token, bookSku)
      setBooks((currentBooks) => currentBooks.filter((entry) => entry.sku !== bookSku))
      if (editingSku === bookSku) {
        resetForm()
      }
      setSuccess('Book deleted successfully.')
    } catch (deleteError) {
      setError(deleteError.message || 'Unable to delete the book.')
    }
  }

  return (
    <div className="min-h-screen bg-[linear-gradient(180deg,#f6f1f1_0%,#fbfaf8_35%,#ffffff_100%)] px-4 py-6 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl">
        <header className="overflow-hidden rounded-3xl border border-[#ecdede] bg-white shadow-[0_18px_50px_-24px_rgba(93,49,51,0.25)]">
          <div className="flex flex-col gap-6 p-5 sm:p-6 lg:flex-row lg:items-end lg:justify-between">
            <div className="max-w-3xl space-y-3">
              <div className="inline-flex items-center gap-2 rounded-full border border-[#ead6d6] bg-[#fff7f7] px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-[var(--maroon)]">
                <BookOpen className="h-3.5 w-3.5" />
                Books manager
              </div>
              <div>
                <h1 className="title-font text-3xl font-bold text-[var(--maroon)] sm:text-4xl">
                  Manage the book catalog
                </h1>
                <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-700 sm:text-base">
                  Add new titles, edit existing ones, and keep the current hardcoded catalog ready for a future API without changing the admin workflow.
                </p>
              </div>
              <p className="text-sm text-slate-600">
                Signed in as {session?.admin?.email || 'Admin'}
              </p>
            </div>

            <div className="flex flex-wrap gap-3">
              <Link
                to="/admin"
                className="inline-flex items-center gap-2 rounded-xl border border-[#e5d3d3] px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
              >
                <ArrowLeft className="h-4 w-4" />
                Back to orders
              </Link>
              <button
                onClick={handleRefresh}
                disabled={loading}
                className="inline-flex items-center gap-2 rounded-xl border border-[#e5d3d3] px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"
              >
                <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
                Refresh
              </button>
              <button
                onClick={handleResetCatalog}
                disabled={loading}
                className="inline-flex items-center gap-2 rounded-xl bg-[var(--maroon)] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[var(--maroon-hover)] disabled:cursor-not-allowed disabled:opacity-60"
              >
                <Sparkles className="h-4 w-4" />
                Restore default books
              </button>
              <button
                onClick={() => {
                  logoutAdmin()
                  navigate('/admin/login', { replace: true })
                }}
                className="inline-flex items-center gap-2 rounded-xl border border-[#e5d3d3] px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
              >
                Logout
              </button>
            </div>
          </div>
        </header>

        <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {stats.map((stat) => (
            <article
              key={stat.label}
              className="rounded-2xl border border-[#eddede] bg-white p-4 shadow-sm"
            >
              <p className="text-sm text-slate-600">{stat.label}</p>
              <p className="mt-2 text-3xl font-bold text-[var(--maroon)]">{stat.value}</p>
            </article>
          ))}
        </section>

        {error ? (
          <div className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>
        ) : null}

        {success ? (
          <div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">
            {success}
          </div>
        ) : null}

        <div className="mt-6 grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
          <section className="order-2 xl:order-1">
            <div className="rounded-3xl border border-[#ecdede] bg-white p-4 shadow-sm sm:p-6">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h2 className="title-font text-2xl font-bold text-[var(--maroon)]">Book library</h2>
                  <p className="mt-1 text-sm text-slate-600">
                    Search, filter, and update the book cards that power the storefront.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  {[
                    { key: 'all', label: 'All' },
                    { key: 'bilingual', label: 'Bilingual' },
                    { key: 'english', label: 'English' },
                    { key: 'punjabi', label: 'Punjabi' },
                  ].map((option) => (
                    <button
                      key={option.key}
                      onClick={() => setFilterMode(option.key)}
                      className={`rounded-full border px-4 py-2 text-sm font-semibold transition ${
                        filterMode === option.key
                          ? 'border-[var(--maroon)] bg-[var(--maroon)] text-white'
                          : 'border-[#e5d3d3] bg-white text-slate-700 hover:bg-slate-50'
                      }`}
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              </div>

              <div className="mt-5 flex flex-col gap-3 md:flex-row md:items-center">
                <div className="flex items-center gap-2 rounded-2xl border border-[#e7dede] bg-[#fcfbfb] px-4 py-3 md:flex-1">
                  <Search className="h-4 w-4 text-slate-400" />
                  <input
                    value={searchQuery}
                    onChange={(event) => setSearchQuery(event.target.value)}
                    placeholder="Search by title, sku, author, or language"
                    className="w-full bg-transparent text-sm outline-none placeholder:text-slate-400"
                  />
                </div>
                <button
                  onClick={() => {
                    resetForm()
                    setSuccess('Ready to add a new book.')
                  }}
                  className="inline-flex items-center justify-center gap-2 rounded-2xl border border-[#e5d3d3] px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
                >
                  <Plus className="h-4 w-4" />
                  Add book
                </button>
              </div>

              <div className="mt-6 grid gap-4 sm:grid-cols-2">
                {filteredBooks.length === 0 ? (
                  <div className="col-span-full rounded-2xl border border-dashed border-[#e7dede] bg-[#fcfbfb] px-6 py-10 text-center text-sm text-slate-600">
                    No books match your current search or filter.
                  </div>
                ) : null}

                {filteredBooks.map((book) => {
                  const isEditing = editingSku === book.sku
                  return (
                    <article
                      key={book.sku}
                      className={`overflow-hidden rounded-2xl border bg-white shadow-[0_12px_30px_-20px_rgba(93,49,51,0.25)] transition hover:-translate-y-0.5 ${
                        isEditing ? 'border-[var(--maroon)] ring-1 ring-[var(--maroon)]' : 'border-[#ecdede]'
                      }`}
                    >
                      <div className="aspect-[16/10] overflow-hidden bg-[#f7f3ef]">
                        <img
                          src={book.uri}
                          alt={book.title}
                          className="h-full w-full object-cover"
                          onError={(event) => {
                            event.currentTarget.src = '/assets/demo.jpg'
                          }}
                        />
                      </div>
                      <div className="space-y-3 p-4">
                        <div className="flex items-start justify-between gap-3">
                          <div>
                            <h3 className="text-base font-semibold text-slate-900">{book.title}</h3>
                            <p className="text-sm text-slate-600">by {book.author}</p>
                          </div>
                          {isEditing ? (
                            <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">
                              <CheckCircle2 className="h-3.5 w-3.5" /> Editing
                            </span>
                          ) : null}
                        </div>

                        <div className="flex flex-wrap gap-2 text-xs font-semibold">
                          <span className="rounded-full bg-slate-100 px-2.5 py-1 text-slate-700">
                            {book.sku}
                          </span>
                          <span className="rounded-full bg-[#fff3dd] px-2.5 py-1 text-[#9a5f00]">
                            {getBookLanguageSummary(book)}
                          </span>
                          <span className="rounded-full bg-[#eef7ff] px-2.5 py-1 text-[#1d5e8a]">
                            {book.pages} pages
                          </span>
                        </div>

                        <p className="line-clamp-3 text-sm leading-6 text-slate-600">
                          {book.description}
                        </p>

                        <div className="flex items-center justify-between gap-3 pt-1">
                          <div>
                            <p className="text-xs uppercase tracking-[0.16em] text-slate-400">Price</p>
                            <p className="text-lg font-bold text-[var(--maroon)]">
                              {formatCurrency(book.pricePaise || book.price * 100)}
                            </p>
                          </div>
                          <div className="flex gap-2">
                            <button
                              onClick={() => beginEditBook(book)}
                              className="inline-flex items-center gap-2 rounded-xl border border-[#e5d3d3] px-3 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
                            >
                              <Edit3 className="h-4 w-4" />
                              Edit
                            </button>
                            <button
                              onClick={() => handleDeleteBook(book.sku)}
                              className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 transition hover:bg-red-50"
                            >
                              <Trash2 className="h-4 w-4" />
                              Delete
                            </button>
                          </div>
                        </div>
                      </div>
                    </article>
                  )
                })}
              </div>
            </div>
          </section>

          <aside className="order-1 xl:order-2">
            <div className="sticky top-6 rounded-3xl border border-[#ecdede] bg-white p-4 shadow-sm sm:p-6">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <h2 className="title-font text-2xl font-bold text-[var(--maroon)]">
                    {editingSku ? 'Edit book' : 'Add a book'}
                  </h2>
                  <p className="mt-1 text-sm text-slate-600">
                    Keep the data hardcoded for now. Later this form can point to your API without changing the UI.
                  </p>
                </div>
                <div className="rounded-2xl bg-[#fff5f5] p-3 text-[var(--maroon)]">
                  <Languages className="h-5 w-5" />
                </div>
              </div>

              <form className="mt-6 space-y-4" onSubmit={handleSaveBook}>
                <div className="grid gap-4 sm:grid-cols-2">
                  <label className="space-y-2 text-sm font-semibold text-slate-700">
                    Title
                    <input
                      value={form.title}
                      onChange={(event) => handleFieldChange('title', event.target.value)}
                      className="w-full rounded-2xl border border-[#e5d3d3] px-4 py-3 text-sm outline-none transition focus:border-[var(--maroon)]"
                      placeholder="Illami Punjab"
                      required
                    />
                  </label>

                  <label className="space-y-2 text-sm font-semibold text-slate-700">
                    SKU
                    <div className="flex overflow-hidden rounded-2xl border border-[#e5d3d3] focus-within:border-[var(--maroon)]">
                      <input
                        value={form.sku}
                        onChange={(event) => handleFieldChange('sku', event.target.value)}
                        readOnly={Boolean(editingSku)}
                        className="w-full px-4 py-3 text-sm outline-none read-only:bg-slate-50"
                        placeholder="Auto-generated from title"
                      />
                      <button
                        type="button"
                        onClick={() => {
                          setForm((prev) => ({ ...prev, sku: slugifyBookTitle(prev.title) }))
                          setSkuAutoGenerated(true)
                        }}
                        className="border-l border-[#e5d3d3] bg-[#fbf8f8] px-3 text-xs font-semibold text-[var(--maroon)] transition hover:bg-[#f7efef]"
                      >
                        Auto
                      </button>
                    </div>
                  </label>
                </div>

                <div className="grid gap-4 sm:grid-cols-2">
                  <label className="space-y-2 text-sm font-semibold text-slate-700">
                    Author
                    <input
                      value={form.author}
                      onChange={(event) => handleFieldChange('author', event.target.value)}
                      className="w-full rounded-2xl border border-[#e5d3d3] px-4 py-3 text-sm outline-none transition focus:border-[var(--maroon)]"
                      placeholder="Rebecca Yarros"
                      required
                    />
                  </label>

                  <label className="space-y-2 text-sm font-semibold text-slate-700">
                    URI
                    <input
                      value={form.uri}
                      onChange={(event) => handleFieldChange('uri', event.target.value)}
                      className="w-full rounded-2xl border border-[#e5d3d3] px-4 py-3 text-sm outline-none transition focus:border-[var(--maroon)]"
                      placeholder="https://..."
                      required
                    />
                  </label>
                </div>

                <div className="grid gap-4 sm:grid-cols-2">
                  <label className="space-y-2 text-sm font-semibold text-slate-700">
                    Pages
                    <input
                      value={form.pages}
                      onChange={(event) => handleFieldChange('pages', event.target.value)}
                      type="number"
                      min="1"
                      className="w-full rounded-2xl border border-[#e5d3d3] px-4 py-3 text-sm outline-none transition focus:border-[var(--maroon)]"
                      placeholder="320"
                      required
                    />
                  </label>

                  <label className="space-y-2 text-sm font-semibold text-slate-700">
                    Price
                    <input
                      value={form.price}
                      onChange={(event) => handleFieldChange('price', event.target.value)}
                      type="number"
                      min="1"
                      className="w-full rounded-2xl border border-[#e5d3d3] px-4 py-3 text-sm outline-none transition focus:border-[var(--maroon)]"
                      placeholder="299"
                      required
                    />
                  </label>
                </div>

                <label className="block space-y-2 text-sm font-semibold text-slate-700">
                  Description
                  <textarea
                    value={form.description}
                    onChange={(event) => handleFieldChange('description', event.target.value)}
                    rows="4"
                    className="w-full rounded-2xl border border-[#e5d3d3] px-4 py-3 text-sm outline-none transition focus:border-[var(--maroon)]"
                    placeholder="A short, clear summary of the book."
                    required
                  />
                </label>

                <div className="rounded-2xl border border-[#eedfdf] bg-[#fcfaf9] p-4">
                  <div className="flex items-center justify-between gap-4">
                    <div>
                      <p className="text-sm font-semibold text-slate-800">Language visibility</p>
                      <p className="text-xs text-slate-500">
                        If bilingual is on, both English and Punjabi are enabled automatically.
                      </p>
                    </div>
                    <label className="flex items-center gap-2 rounded-full border border-[#e5d3d3] bg-white px-3 py-2 text-sm font-semibold text-slate-700">
                      <input
                        type="checkbox"
                        checked={form.bilangual}
                        onChange={(event) => handleBilingualToggle(event.target.checked)}
                        className="h-4 w-4 accent-[var(--maroon)]"
                      />
                      Bilingual
                    </label>
                  </div>

                  <div className="mt-4 grid gap-3 sm:grid-cols-2">
                    <label className={`flex items-center gap-3 rounded-2xl border px-4 py-3 text-sm font-medium ${form.bilangual ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-[#e5d3d3] bg-white text-slate-700'}`}>
                      <input
                        type="checkbox"
                        checked={form.onlyEnglish}
                        disabled={form.bilangual}
                        onChange={(event) => handleLanguageToggle('onlyEnglish', event.target.checked)}
                        className="h-4 w-4 accent-[var(--maroon)] disabled:opacity-60"
                      />
                      English
                    </label>
                    <label className={`flex items-center gap-3 rounded-2xl border px-4 py-3 text-sm font-medium ${form.bilangual ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-[#e5d3d3] bg-white text-slate-700'}`}>
                      <input
                        type="checkbox"
                        checked={form.onpunjabi}
                        disabled={form.bilangual}
                        onChange={(event) => handleLanguageToggle('onpunjabi', event.target.checked)}
                        className="h-4 w-4 accent-[var(--maroon)] disabled:opacity-60"
                      />
                      Punjabi
                    </label>
                  </div>
                </div>

                <div className="grid gap-4 sm:grid-cols-[1fr_auto]">
                  <button
                    type="submit"
                    disabled={saving}
                    className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[var(--maroon)] px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-[var(--maroon-hover)] disabled:cursor-not-allowed disabled:opacity-60"
                  >
                    {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                    {editingSku ? 'Update book' : 'Save book'}
                  </button>
                  <button
                    type="button"
                    onClick={resetForm}
                    className="rounded-2xl border border-[#e5d3d3] px-5 py-3.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
                  >
                    Clear form
                  </button>
                </div>
              </form>

              <div className="mt-6 rounded-2xl border border-dashed border-[#e6dede] bg-[#fcfbfb] p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Preview</p>
                {form.uri ? (
                  <div className="mt-3 overflow-hidden rounded-2xl border border-[#eadede] bg-white">
                    <div className="aspect-[16/9] bg-[#f7f3ef]">
                      <img
                        src={form.uri}
                        alt={form.title || 'Book preview'}
                        className="h-full w-full object-cover"
                        onError={(event) => {
                          event.currentTarget.src = '/assets/demo.jpg'
                        }}
                      />
                    </div>
                    <div className="p-4">
                      <h3 className="font-semibold text-slate-900">
                        {form.title || 'Title preview'}
                      </h3>
                      <p className="mt-1 text-sm text-slate-600">
                        {form.author || 'Author preview'}
                      </p>
                      <p className="mt-3 text-sm text-slate-500">
                        {form.sku || 'Auto-generated sku will appear here'}
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="mt-3 flex min-h-40 items-center justify-center rounded-2xl border border-[#eadede] bg-white text-sm text-slate-500">
                    Enter a URI to see the preview.
                  </div>
                )}
              </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  )
}

export default AdminBooksPage
